### PR TITLE
Add coordinate properties for times and heartRates

### PR DESCRIPTION
**Pull request by RalucaNicola**
Addresses issue https://github.com/tmcw/togeojson/issues/29.

This PR moves the `coordTimes` and `heartRates` properties into a parent property `coordinateProperties`:
- kml: `coordTimes` is moved into `coordinateProperties.times`
- gpx: `coordTimes` and `heartRates` are moved into `coordinateProperties.times` and `coordinateProperties.heartRates`
- tcx: `coordTimes` and `heartRates` are moved into `coordinateProperties.times` and `coordinateProperties.heartRates`

### CODE REVIEW

**Comment by RalucaNicola** [comment]
Finally made a PR @tmcw. When you get a chance, let me know if my approach is going in the right direction here :) thanks!

**Comment by tmcw** [comment]
Ah, sorry I missed this notification! Reviewing this today.

**Review by tmcw — APPROVED** [review]
👍 Perfect! Took me a little while to wrap my head around the gpx implementation, but it seems pretty ideal. Thanks, merging.

**Comment by RalucaNicola** [comment]
awesome, thanks for reviewing 🥳

**Pull request merged**
