### PR TITLE
feat: add garmin extension handling

### LINKED ISSUE #19: feature request: add support for styles
Hey there,

happy to see this project is still maintained - thank you for that!

One question I'd like to raise is if there are plans to map the .gpx styles to the .geojson format as well. The so-called "[Geojson CSS](https://wiki.openstreetmap.org/wiki/Geojson_CSS)" markup is used for that and could be applied from the `gpxx:DisplayColor` GPX attribute. I could contribute that change if the general idea is approved by you.

Thanks!

**EDIT**: It seems like basic styles are already supported [here](https://github.com/tmcw/togeojson/blob/master/lib/gpx.js#L11-L26) but it seems limited to certain styles. The latest Garmin routes have a format as following:
```xml
  <rte>
    <name>27.05.2020 Tour 5_357 km_zyanblau</name>
    <extensions>
      <gpxx:RouteExtension>
        <gpxx:IsAutoNamed>false</gpxx:IsAutoNamed>
        <gpxx:DisplayColor>Cyan</gpxx:DisplayColor>
      </gpxx:RouteExtension>
      <trp:Trip>
        <trp:TransportationMode>Motorcycling</trp:TransportationMode>
      </trp:Trip>
    </extensions>
    ...
  </rte>
```

### PR DESCRIPTION
**Pull request by hansemannn**
Fixes #19

### CODE REVIEW

**Comment by tmcw** [comment]
Looking good! Only thing missing is a test. Can you add an example of a GPX file that uses these attributes into `test/data` and run `npm test -u` to add a snapshot of the new result?

**Comment by hansemannn** [comment]
I just added it but receiving the following while executing the test (happens even if a duplicate and rename an existing gpx file):
```
> @tmcw/togeojson@3.1.0 test /Users/hans/Documents/dev/togeojson
> eslint lib && jest

 FAIL  test/index.test.js
  ✕ toGeoJSON (5ms)

  ● toGeoJSON

    TypeError: tj[_path2.default.extname(...).substring(...)] is not a function

       9 |   for (let file of fs.readdirSync(d)) {
      10 |     expect(
    > 11 |       tj[path.extname(file).substring(1)](
         |       ^
      12 |         new xmldom.DOMParser().parseFromString(
      13 |           fs.readFileSync(path.join(d, file), "utf8")
      14 |         )

      at Object.<anonymous> (test/index.test.js:11:7)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.623s, estimated 1s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by tmcw** [comment]
Well, that's weird! Tests are looking broken for me too, maybe because of a node version change. I'll fix them and probably replace Jest - just drop the gpx fixture in this branch and I'll work from there.

**Comment by hansemannn** [comment]
Yep, could be. It may be the rollup of the library thats used with a wildcard import (`*`) - let me know if I can help further!

**Comment by tmcw** [comment]
Okay! I've switched the test setup to more closely match my overall defaults. Mind rebasing on top of master, then

```
$ TAP_SNAPSHOT=1 npm test
```

Will run & update test fixtures.

**Comment by hansemannn** [comment]
It still does not work, sorry!
```
 FAIL  test/index.test.js 1 failed of 1 17.801ms
 ✖ tj[path.extname(...).substring(...)] is not a function



  🌈 SUMMARY RESULTS 🌈


 FAIL  test/index.test.js 1 failed of 1 17.801ms
 ✖ tj[path.extname(...).substring(...)] is not a function

Suites:   1 failed, 1 of 1 completed
Asserts:  1 failed, of 1
Time:     774.948ms
---------------|----------|----------|----------|----------|-------------------|
File           |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------|----------|----------|----------|----------|-------------------|
All files      |     1.48 |        0 |        0 |     1.73 |                   |
 togeojson     |        0 |        0 |        0 |        0 |                   |
  index.js     |        0 |        0 |        0 |        0 |                   |
 togeojson/lib |     1.48 |        0 |        0 |     1.73 |                   |
  gpx.js       |     0.72 |        0 |        0 |     0.85 |... 50,252,253,258 |
  kml.js       |     2.04 |        0 |        0 |     2.38 |... 04,305,311,316 |
  shared.js    |        0 |        0 |        0 |        0 |             4,5,7 |
---------------|----------|----------|----------|----------|-------------------|
npm ERR! Test failed.  See above for more details.
```

Also, the dev-dependency `diff` was missing in the package.json, I added it via `npm i --save-dev diff`.

**Comment by hansemannn** [comment]
Okay, that was a long journey. Apparently, a `.DS_STORE` file in `test/data` caused the whole file-suffix-to-function-call logic to crash. So I added two additional lines:
1. Check for hidden files in the file loop and ignore them (0117955)
2. Add the missing `diff` dependency via `npm i --save-dev diff` (eba81e5)

I hope it's good to go now. Thanks for your long breath on this!

**Comment by tmcw** [comment]
Okay, I'll work on merging this in today. In terms of `diff` - why was that added? Nowhere is `diff` directly imported or required by this library. Possibly that was an npm bug?

**Comment by tmcw** [comment]
👍 Okay, I've generalized this to include all gpxx extensions in #20 and released as 3.2.0! Thanks for your help.

**Comment by hansemannn** [comment]
Thanks! Thats even better. The style of the key names looks a bit odd and could be replaced by hyphons, but this makes it usable already.

**Pull request closed without merging**
